flags:
  generic-deriving:
    base-4-9: false
extra-package-dbs: []
packages:
- .
extra-deps:
- Cabal-1.24.2.0
- StateVar-1.1.0.4
- adjunctions-4.3
- base-orphans-0.6
- bifunctors-5.4.2
- bytes-0.15.3
- cabal-doctest-1.0.2
- cairo-0.13.3.1
- cereal-0.5.4.0
- comonad-5.0.1
- contravariant-1.4
- distributive-0.5.2
- elerea-2.9.0
- exceptions-0.8.3
- fail-4.9.0.0
- free-4.12.4
- generic-deriving-1.11.2
- glib-0.13.4.1
- gtk2hs-buildtools-0.13.2.2
- hashable-1.2.6.1
- hashtables-1.2.1.1
- helm-1.0.0
- integer-logarithms-1.0.2
- kan-extensions-5.0.2
- lens-4.15.3
- linear-1.20.6
- mtl-2.2.1
- pango-0.13.3.1
- parallel-3.2.1.1
- prelude-extras-0.4.0.3
- primitive-0.6.2.0
- profunctors-5.2
- random-1.1
- reflection-2.1.2
- scientific-0.3.5.1
- sdl2-2.2.0
- semigroupoids-5.2
- semigroups-0.18.3
- stm-2.4.4.1
- tagged-0.8.5
- text-1.2.2.2
- th-abstraction-0.2.3.0
- transformers-0.5.4.0
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unordered-containers-0.2.8.0
- utf8-string-1.0.1.1
- vector-0.12.0.1
- void-0.7.2
resolver: ghc-7.10
